# Override per ambiente di sviluppo
# Usa: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  tenant-service:
    # In sviluppo, usa il Dockerfile normale se preferisci
    build:
      context: .
      dockerfile: srcTenantService/TenantService/Dockerfile.multistage
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
      # Variabili per controllare il comportamento delle migrazioni
      - FORCE_LOCAL_PROJECT_PATH=true           # Forza l'uso dei path locali anche in Docker
      - SKIP_TENANT_MIGRATIONS=false            # Abilita le migrazioni (default)
    volumes:
      # Monta la directory della solution per sviluppo
      - .:/src:ro
