# Override per ambiente di sviluppo
# Usa: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  building-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Services__AttachmentService__Url=http://attachment-service:8080
  
  attachment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  tenant-service:
    # In sviluppo, usa il Dockerfile normale se preferisci
    build:
      context: .
      dockerfile: srcTenantService/TenantService/Dockerfile.multistage
    environment:
      - ASPNETCORE_ENVIRONMENT=Production        # Usa Production per i path Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
      # Disabilita force local path per usare i path Docker
      # - FORCE_LOCAL_PROJECT_PATH=true           
      - SKIP_TENANT_MIGRATIONS=false            # Abilita le migrazioni
    # Rimuoviamo i volumi per usare i sorgenti nel container
    # volumes:
    #   # Monta la directory della solution per sviluppo
    #   - .:/src:ro
