services:
  postgres-db:
    image: postgres:16
    container_name: remax-postgres
    restart: always
    environment:
      POSTGRES_DB: remax_management
      POSTGRES_USER: remax_user
      POSTGRES_PASSWORD: remax_password123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - remax-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U remax_user -d remax_management"]
      interval: 30s
      timeout: 10s
      retries: 3

  authentication-service:
    build:
      context: .
      dockerfile: srcAuthenticationService/AuthenticationService/Dockerfile.multistage
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  building-service:
    build:
      context: .
      dockerfile: srcBuildingService/BuildingService/Dockerfile.multistage
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  workquote-service:
    build:
      context: .
      dockerfile: srcWorkQuoteService/WorkQuoteService/Dockerfile.multistage
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  workorder-service:
    build:
      context: .
      dockerfile: srcWorkOrderService/WorkOrderService/Dockerfile.multistage
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  rfq-service:
    build:
      context: .
      dockerfile: srcRfqService/RfqService/Dockerfile.multistage
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  worksheet-service:
    build:
      context: .
      dockerfile: srcWorkSheetService/WorkSheetService/Dockerfile.multistage
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  users-service:
    build:
      context: .
      dockerfile: srcUsersService/UsersService/Dockerfile.multistage
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  attachment-service:
    build:
      context: .
      dockerfile: srcAttachmentService/AttachmentService/Dockerfile.multistage
    ports:
      - "5009:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  supplier-service:
    build:
      context: .
      dockerfile: srcSupplierService/SupplierService/Dockerfile.multistage
    ports:
      - "5010:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  communication-service:
    build:
      context: .
      dockerfile: srcCommunicationService/CommunicationService/Dockerfile.multistage
    ports:
      - "5011:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  issue-service:
    build:
      context: .
      dockerfile: srcIssueService/IssueService/Dockerfile.multistage
    ports:
      - "5012:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  maintenance-service:
    build:
      context: .
      dockerfile: srcMaintenanceService/MaintenanceService/Dockerfile.multistage
    ports:
      - "5013:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  insurance-service:
    build:
      context: .
      dockerfile: srcInsuranceService/InsuranceService/Dockerfile.multistage
    ports:
      - "5014:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  checklist-service:
    build:
      context: .
      dockerfile: srcCheckListService/CheckListService/Dockerfile.multistage
    ports:
      - "5015:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  remax-network:
    driver: bridge
