version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: remax-postgres
    restart: always
    environment:
      POSTGRES_DB: remax_management
      POSTGRES_USER: remax_user
      POSTGRES_PASSWORD: remax_password123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - remax-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U remax_user -d remax_management"]
      interval: 30s
      timeout: 10s
      retries: 3

  authentication-service:
    build:
      context: ./srcAuthenticationService/AuthenticationService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  building-service:
    build:
      context: ./srcBuildingService/BuildingService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  workquote-service:
    build:
      context: ./srcWorkQuoteService/WorkQuoteService
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  workorder-service:
    build:
      context: ./srcWorkOrderService/WorkOrderService
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  rfq-service:
    build:
      context: ./srcRfqService/RfqService
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  worksheet-service:
    build:
      context: ./srcWorkSheetService/WorkSheetService
      dockerfile: Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  asset-service:
    build:
      context: ./srcAssetService/AssetService
      dockerfile: Dockerfile
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  users-service:
    build:
      context: ./srcUsersService/UsersService
      dockerfile: Dockerfile
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

  attachment-service:
    build:
      context: ./srcAttachmentService/AttachmentService
      dockerfile: Dockerfile
    ports:
      - "5009:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=remax_management;Username=remax_user;Password=remax_password123;Port=5432
    networks:
      - remax-network
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  remax-network:
    driver: bridge