// <auto-generated />
using System;
using InsuranceService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsuranceService.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20250814121313_AddInsuranceForeignKeyConstraints")]
    partial class AddInsuranceForeignKeyConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsuranceService.Data.Entities.Insurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AgentPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("AgreementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fractionation")
                        .HasColumnType("double precision");

                    b.Property<double>("InsurancePremium")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("PolicyDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Previsions")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReceiptDocumentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PolicyDocumentId")
                        .HasDatabaseName("IX_Insurances_PolicyDocumentId");

                    b.HasIndex("ReceiptDocumentId")
                        .HasDatabaseName("IX_Insurances_ReceiptDocumentId");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceAccidents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AmountPaid")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("EstimatedDamage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("InsuranceId")
                        .HasColumnType("uuid");

                    b.Property<int>("PracticalStatus")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("IX_InsuranceAccidents_BuildingId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsuranceAccidents");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceAccidentsIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("InsuranceAccidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceAccidentId");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("IX_InsuranceAccidentsIssues_IssueId");

                    b.ToTable("InsuranceAccidentsIssues");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceAccidentsWorksPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("InsuranceAccidentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceAccidentId");

                    b.HasIndex("WorkPlanId")
                        .HasDatabaseName("IX_InsuranceAccidentsWorksPlans_WorkPlanId");

                    b.ToTable("InsuranceAccidentsWorksPlans");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceDeductible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Guarantee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InsuranceId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsuranceDeductibles");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceLimits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Guarantee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InsuranceId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsuranceLimits");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceAccidents", b =>
                {
                    b.HasOne("InsuranceService.Data.Entities.Insurance", null)
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InsuranceAccidents_Insurances_InsuranceId");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceAccidentsIssue", b =>
                {
                    b.HasOne("InsuranceService.Data.Entities.InsuranceAccidents", null)
                        .WithMany()
                        .HasForeignKey("InsuranceAccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InsuranceAccidentsIssues_InsuranceAccidents_InsuranceAccidentId");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceAccidentsWorksPlan", b =>
                {
                    b.HasOne("InsuranceService.Data.Entities.InsuranceAccidents", null)
                        .WithMany()
                        .HasForeignKey("InsuranceAccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InsuranceAccidentsWorksPlans_InsuranceAccidents_InsuranceAccidentId");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceDeductible", b =>
                {
                    b.HasOne("InsuranceService.Data.Entities.Insurance", null)
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InsuranceDeductibles_Insurances_InsuranceId");
                });

            modelBuilder.Entity("InsuranceService.Data.Entities.InsuranceLimits", b =>
                {
                    b.HasOne("InsuranceService.Data.Entities.Insurance", null)
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InsuranceLimits_Insurances_InsuranceId");
                });
#pragma warning restore 612, 618
        }
    }
}
